//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid19Website
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sick
    {
        public int SickID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Tel { get; set; }
        public int NationalityID { get; set; }
        public System.DateTime SickDate { get; set; }
        public int Number { get; set; }
    
        public virtual Nationality Nationality { get; set; }
    }
}
